### ISSUE TITLE
avahi-in-safarii.png is missing

### ISSUE THREAD

**Issue by tomjn** [sosheskaz/sosheskaz.github.io#5]
https://sosheskaz.github.io/files/images/posts/2016-09-26-avahi-in-safari.png doesn't exist anymore, resulting in a broken img tag at https://sosheskaz.github.io/tutorial/2016/09/26/Avahi-HTTP-Service.html

**Comment by sosheskaz** [comment]
@tomjn I've restored the image, which has fixed the issue. Thank you for bringing this to my attention.
